openapi: 3.0.0
info:
  version: "0.1.0"
  title: Parley
tags:
  - name: Unauthenticated
  - name: Authenticated
paths:
  /:
    get:
      tags:
        - Unauthenticated
      summary: Gets basic info
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  running:
                    type: string
                    enum: [Parley]
                    example: Parley
                  version:
                    type: string
                    example: 0.1.0
  /login:
    post:
      tags:
        - Unauthenticated
      summary: Log in
      responses:
        '200':
          description: All valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/challenge"
        '400':
          description: Public doesn't match
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
        '401':
          description: Invalid username or passkey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - passkey
                - public
              properties:
                username:
                  type: string
                passkey:
                  type: string
                public:
                  type: string
  /signup:
    post:
      tags:
        - Unauthenticated
      summary: Sign up
      responses:
        '200':
          description: All valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/challenge"
        '400':
          description: Username in use
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
        '401':
          description: Invalid public key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - public
              properties:
                username:
                  type: string
                public:
                  type: string
  /username_check:
    get:
      tags:
        - Unauthenticated
      summary: Check username
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
          description: Username
      responses:
        '200':
          description: Available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/valid"
        '400':
          description: Username in use
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
  /solve:
    post:
      tags:
        - Unauthenticated
      summary: Solve challenge
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
                - solve
              properties:
                id:
                  type: string
                solve:
                  type: string
      responses:
        '200':
          description: Valid
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/valid"
                  - $ref: '#/components/schemas/loginresponse'
                  - $ref: '#/components/schemas/signupresponse'
        '400':
          description: Unknown challenge id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
        '401':
          description: Invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
  /me:
    get:
      tags:
        - Authenticated
      summary: Get current user
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: "Men"
                  display:
                    type: string
                    example: "s'embrassant"
                  pfp:
                    type: string
                    example: "https://.../image.png"
        '401':
          description: Missing authorization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
  /channels:
    get:
      tags:
        - Authenticated
      summary: Get user channels
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1234"
                    name:
                      type: string
                      example: "Friend"
                    picture:
                      type: string
                      example: "https://.../image.png"
        '401':
          description: Missing authorization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
  /messages:
    get:
      tags:
        - Authenticated
      summary: Get the messages of a channel
      parameters:
        - in: query
          name: channel
          schema:
            type: string
          required: true
          description: ID of channel
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["Message","AESKeyExchange"]
                      example: "Message"
                    content:
                      type: string
                      example: "Encrypted object"
                    timestamp:
                      type: string
                      example: "Unix ms"
        '401':
          description: Missing authorization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
  /reset-keys:
    post:
      tags:
        - Authenticated
      summary: Reset public and private keys
      responses:
        '200':
          description: Valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/challenge"
        '400':
          description: Invalid public key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
        '401':
          description: Missing authorization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - public
              properties:
                public:
                  type: string
components:
  schemas:
    challenge:
      type: object
      properties:
        id:
          type: string
          example: Identifier
        challenge:
          type: string
          example: Encrypted value
    valid:
      type: object
      properties:
        success:
          type: boolean
          example: true
    invalid:
      type: object
      properties:
        success:
          type: boolean
          example: false

    loginresponse:
      type: object
      properties:
        session:
          type: string
          example: Token
    signupresponse:
      type: object
      properties:
        session:
          type: string
          example: Token
        passkey:
          type: string
          example: Passkey