openapi: 3.0.0
info:
  version: "0.1.0"
  title: Parley
tags:
  - name: Unauthenticated
  - name: Authenticated
paths:
  /:
    get:
      tags:
        - Unauthenticated
      summary: Gets basic info
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  running:
                    type: string
                    enum: [Parley]
                    example: Parley
                  version:
                    type: string
                    example: 0.1.0
  /login:
    post:
      tags:
        - Unauthenticated
      summary: Login
      responses:
        '200':
          description: All valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  challenge:
                    type: string
                    example: Encrypted value
        '400':
          description: Public doesn't match
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
        '401':
          description: Invalid username or passkey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - passkey
                - publickey
              properties:
                username:
                  type: string
                passkey:
                  type: string
                publickey:
                  type: string
  /solve:
    post:
      tags:
        - Unauthenticated
      summary: Solve challenge
      responses:
        '200':
          description: Valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/valid"
        '401':
          description: Invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/invalid"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - solve
              properties:
                solve:
                  type: string
  /channels:
    get:
      tags:
        - Authenticated
      summary: Get user channels
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    schema:
                      $ref: "#/components/schemas/channel"
components:
  schemas:
    valid:
      type: object
      properties:
        success:
          type: boolean
          example: true
    invalid:
      type: object
      properties:
        success:
          type: boolean
          example: false
    channel:
      type: object
      properties:
        id:
          type: string
          example: "1234"
        name:
          type: string
          example: "Friend"
        picture:
          type: string
          example: "https://.../image.png"